import type { ProductPageBlockSchema, ProductPageBlockType } from "./types";

export const PRODUCT_PAGE_BLOCK_REGISTRY: Record<
  ProductPageBlockType,
  ProductPageBlockSchema
> = {
  gallery: {
    type: "gallery",
    label: "Galerie images",
    description: "Photos produit et miniatures",
    icon: "camera",
    zone: "main",
    locked: true,
    fields: [
      { key: "showTag", label: "Afficher le tag promo", type: "boolean" },
    ],
  },
  product_info: {
    type: "product_info",
    label: "Informations produit",
    description: "Nom, prix, catégorie, stock",
    icon: "tag",
    zone: "main",
    locked: true,
    fields: [
      { key: "showBestSeller", label: "Badge best-seller", type: "boolean" },
      { key: "showCategory", label: "Catégorie et contenance", type: "boolean" },
      { key: "showStock", label: "Indicateur de stock", type: "boolean" },
    ],
  },
  variants: {
    type: "variants",
    label: "Variantes",
    description: "Sélecteur contenance / teinte",
    icon: "grid",
    zone: "main",
    fields: [],
  },
  quantity: {
    type: "quantity",
    label: "Quantité",
    description: "Sélecteur de quantité",
    icon: "plus",
    zone: "main",
    fields: [{ key: "label", label: "Libellé", type: "text", placeholder: "Quantité" }],
  },
  reference: {
    type: "reference",
    label: "Référence SKU",
    description: "Ligne Réf. sous les avis",
    icon: "info",
    zone: "main",
    fields: [],
  },
  live_viewers: {
    type: "live_viewers",
    label: "Visiteurs en direct",
    description: "Social proof — personnes qui consultent",
    icon: "eye",
    zone: "main",
    fields: [],
  },
  stock_alert: {
    type: "stock_alert",
    label: "Alerte stock",
    description: "Message stock faible (social proof)",
    icon: "bell",
    zone: "main",
    fields: [],
  },
  reviews_summary: {
    type: "reviews_summary",
    label: "Résumé avis",
    description: "Note moyenne et lien vers avis",
    icon: "star",
    zone: "main",
    fields: [],
  },
  benefits: {
    type: "benefits",
    label: "Bénéfices clés",
    description: "Liste à puces (contenu par produit)",
    icon: "check",
    zone: "main",
    fields: [],
  },
  description: {
    type: "description",
    label: "Description",
    description: "Accordéon description (contenu par produit)",
    icon: "info",
    zone: "main",
    fields: [],
  },
  usage_tips: {
    type: "usage_tips",
    label: "Conseils d'utilisation",
    description: "Étapes d'application (contenu par produit)",
    icon: "heart",
    zone: "main",
    fields: [],
  },
  video: {
    type: "video",
    label: "Vidéo produit",
    description: "Vidéo intégrée ou URL externe",
    icon: "play",
    zone: "main",
    fields: [
      { key: "videoUrl", label: "URL vidéo (optionnel)", type: "text", placeholder: "https://…" },
      { key: "autoplay", label: "Lecture automatique", type: "boolean" },
    ],
  },
  faq: {
    type: "faq",
    label: "FAQ",
    description: "Questions fréquentes globales",
    icon: "info",
    zone: "main",
    fields: [
      {
        key: "items",
        label: "Questions / réponses",
        type: "faq_list",
        helpText: "FAQ identique sur toutes les fiches produit",
      },
    ],
  },
  custom: {
    type: "custom",
    label: "Section personnalisée",
    description: "Bloc éditorial libre",
    icon: "sparkle",
    zone: "main",
    fields: [
      { key: "title", label: "Titre", type: "text" },
      {
        key: "sectionType",
        label: "Format",
        type: "text",
        helpText: "text | list | steps — géré dans l'éditeur",
      },
      { key: "body", label: "Contenu texte", type: "textarea" },
    ],
  },
  before_after: {
    type: "before_after",
    label: "Avant / Après",
    description: "Résultats clients",
    icon: "camera",
    zone: "main",
    fields: [],
  },
  reviews: {
    type: "reviews",
    label: "Avis clients",
    description: "Liste complète des avis",
    icon: "star",
    zone: "main",
    fields: [{ key: "title", label: "Titre de section", type: "text" }],
  },
  routine: {
    type: "routine",
    label: "Routine beauté",
    description: "Cross-sell même catégorie",
    icon: "heart",
    zone: "main",
    fields: [{ key: "title", label: "Titre", type: "text" }],
  },
  recommendations: {
    type: "recommendations",
    label: "Recommandations",
    description: "Vous aimerez aussi",
    icon: "bag",
    zone: "main",
    fields: [
      { key: "title", label: "Titre", type: "text" },
      { key: "maxItems", label: "Nombre max.", type: "number" },
    ],
  },
  sales_counter: {
    type: "sales_counter",
    label: "Compteur ventes",
    description: "Social proof ventes récentes",
    icon: "bolt",
    zone: "sticky",
    fields: [],
  },
  add_to_cart: {
    type: "add_to_cart",
    label: "Ajouter au panier",
    description: "Bouton CTA principal",
    icon: "bag",
    zone: "sticky",
    locked: true,
    fields: [
      { key: "ctaLabel", label: "Libellé (vide = défaut)", type: "text" },
      { key: "showPrice", label: "Afficher le prix dans le bouton", type: "boolean" },
    ],
  },
  trust_badges: {
    type: "trust_badges",
    label: "Réassurance",
    description: "Badges livraison, paiement, retours…",
    icon: "check",
    zone: "sticky",
    fields: [],
  },
};

export const ADDABLE_BLOCK_TYPES: ProductPageBlockType[] = [
  "custom",
  "faq",
  "video",
  "benefits",
  "description",
  "usage_tips",
  "before_after",
  "reviews",
  "routine",
  "recommendations",
  "live_viewers",
  "stock_alert",
  "reference",
  "variants",
  "quantity",
];
